services:
  - type: web
    name: odoo17
    env: docker
    plan: starter
    envVars:
      - key: HOST
        fromDatabase:
          name: my-postgres
          property: host
      - key: PORT
        fromDatabase:
          name: my-postgres
          property: port
      - key: USER
        fromDatabase:
          name: my-postgres
          property: user
      - key: PASSWORD
        fromDatabase:
          name: my-postgres
          property: password
      - key: DATABASE
        fromDatabase:
          name: my-postgres
          property: database

databases:
  - name: my-postgres
    plan: starter
