services:
  - type: web
    name: odoo17
    env: docker
    plan: starter
    envVars:
      - key: DATABASE_HOST
        value: dpg-d2hmde7s7bs738bofeg-a
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_USER
        value: admin
      - key: DATABASE_PASSWORD
        value: your_real_password
